[build]
  command = "npm run build"
  publish = "/dist"
  base = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "react"
  command = "npm run dev"
  targetPort = 8083
  port = 8888
  publish = "dist"
  autoLaunch = false
